### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by JakobMiksch** [empatica/empalink-sample-project-android#16]
I updated from SDK 2.0 to 2.2 and get this error.

Any hints how to solve this?

```
04-23 11:40:12.977 8131-8131/? E/Zygote: v2
04-23 11:40:12.979 8131-8131/? E/Zygote: accessInfo : 0
04-23 11:40:13.751 8131-8149/? E/AndroidRuntime: FATAL EXCEPTION: IntentService[EMPATICA_E4]
    Process: fruehling, PID: 8131
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/fruehling-2/base.apk", zip file "/data/app/fruehling-2/split_lib_dependencies_apk.apk", zip file "/data/app/fruehling-2/split_lib_slice_0_apk.apk", zip file "/data/app/fruehling-2/split_lib_slice_1_apk.apk", zip file "/data/app/fruehling-2/split_lib_slice_2_apk.apk", zip file "/data/app/fruehling-2/split_lib_slice_3_apk.apk", zip file "/data/app/fruehling-2/split_lib_slice_4_apk.apk", zip file "/data/app/fruehling-2/split_lib_slice_5_apk.apk", zip file "/data/app/fruehling-2/split_lib_slice_6_apk.apk", zip file "/data/app/fruehling-2/split_lib_slice_7_apk.apk", zip file "/data/app/fruehling-2/split_lib_slice_8_apk.apk", zip file "/data/app/fruehling-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/fruehling-2/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libempac.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:972)
        at java.lang.System.loadLibrary(System.java:1567)
        at com.empatica.empalink.EmpaDeviceManager.<clinit>(EmpaDeviceManager.java:78)
        at fruehling.sensors.empatica.E4$appTask.doInBackground(E4.java:64)
        at fruehling.sensors.empatica.E4.onHandleIntent(E4.java:49)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by felixkosmalla** [comment]
I had the same issue, however, I am not completely sure when it came up.

I could fix it by adding

`ndk {
            abiFilters "armeabi", "armeabi-v7a"
        }
`
to the `defaultConfig` node in `build.gradle`.
